#!/usr/bin/env python3
"""
Demo script: upload -> mapping -> calculation -> results
Uses FastAPI TestClient (no server needed).
Exit 0 on success, 1 on failure.
"""
import argparse
import json
import os
import sys

# Ensure app is importable
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

os.environ.setdefault("DATABASE_URL", "sqlite:////tmp/co2poc_demo.db")

from app.main import app
from app.db.base import Base
from app.db.session import engine, get_db, SessionLocal
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

# Fresh DB for demo
Base.metadata.drop_all(bind=engine)
Base.metadata.create_all(bind=engine)

client = TestClient(app)

FIXTURE = os.path.join(
    os.path.dirname(__file__), "..", "tests", "fixtures", "accounting_sample.csv"
)
MAPPING = {
    "勘定科目コード": "account_code",
    "勘定科目名":     "account_name",
    "数量":           "quantity",
    "単位":           "unit",
    "金額":           "amount",
}


def check(condition, msg):
    if not condition:
        print(f"  FAIL: {msg}", file=sys.stderr)
        sys.exit(1)
    print(f"  OK:   {msg}")


def generate_html_report(summary, path):
    """Generate a standalone HTML report with inline SVG bar chart."""
    s1, s2, s3, total = summary["scope1_total"], summary["scope2_total"], summary["scope3_total"], summary["grand_total"]
    max_val = max(s1, s2, s3, 0.01)
    bar_w = lambda v: int(v / max_val * 300)

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>CO2 Emission Report</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 640px; margin: 2rem auto; color: #222; }}
h1 {{ font-size: 1.4rem; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ padding: 0.5rem 0.8rem; border-bottom: 1px solid #ddd; text-align: left; }}
th {{ background: #f0f0f0; }}
.total td {{ font-weight: 700; background: #f8f8f8; }}
svg {{ margin: 1rem 0; }}
.label {{ font-size: 13px; fill: #444; }}
.val {{ font-size: 12px; fill: #666; }}
</style></head><body>
<h1>CO2 Emission Report</h1>
<table>
<tr><th>Scope</th><th>Emission (kg-CO2e)</th></tr>
<tr><td>Scope 1 (direct)</td><td>{s1:.2f}</td></tr>
<tr><td>Scope 2 (energy indirect)</td><td>{s2:.2f}</td></tr>
<tr><td>Scope 3 (other indirect)</td><td>{s3:.2f}</td></tr>
<tr class="total"><td>Grand Total</td><td>{total:.2f}</td></tr>
</table>
<h2>Scope Breakdown</h2>
<svg width="480" height="140" xmlns="http://www.w3.org/2000/svg">
  <text x="0" y="25" class="label">Scope 1</text>
  <rect x="80" y="10" width="{bar_w(s1)}" height="22" fill="#ef4444" rx="3"/>
  <text x="{85 + bar_w(s1)}" y="27" class="val">{s1:.1f}</text>
  <text x="0" y="65" class="label">Scope 2</text>
  <rect x="80" y="50" width="{bar_w(s2)}" height="22" fill="#3b82f6" rx="3"/>
  <text x="{85 + bar_w(s2)}" y="67" class="val">{s2:.1f}</text>
  <text x="0" y="105" class="label">Scope 3</text>
  <rect x="80" y="90" width="{bar_w(s3)}" height="22" fill="#22c55e" rx="3"/>
  <text x="{85 + bar_w(s3)}" y="107" class="val">{s3:.1f}</text>
</svg>
<p style="font-size:0.8rem;color:#888">Generated by CO2 Emission PoC demo script</p>
</body></html>"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html)


def main(csv_out=None, html_out=None):
    print("=== CO2 Emission PoC - API Demo Flow ===\n")

    # --- Step 0: health ---
    print("[0] Health check")
    r = client.get("/health")
    check(r.status_code == 200, f"GET /health → 200 (got {r.status_code})")
    check(r.json()["status"] == "ok", "status == ok")

    # --- Step 1: upload ---
    print("\n[1] Upload accounting CSV")
    with open(FIXTURE, "rb") as f:
        r = client.post(
            "/api/v1/uploads",
            files={"file": ("accounting_sample.csv", f, "text/csv")},
            data={"data_type": "accounting"},
        )
    check(r.status_code == 201, f"POST /api/v1/uploads → 201 (got {r.status_code})")
    data = r.json()
    upload_id = data["upload_id"]
    check(data["row_count"] == 5, f"row_count == 5 (got {data['row_count']})")
    check(data["status"] == "pending_mapping", "status == pending_mapping")
    print(f"       upload_id={upload_id}")

    # --- Step 2: mapping ---
    print("\n[2] Save column mapping")
    r = client.post(
        f"/api/v1/uploads/{upload_id}/mappings",
        json={"mappings": MAPPING},
    )
    check(r.status_code == 201, f"POST /mappings → 201 (got {r.status_code})")
    mapping_id = r.json()["mapping_id"]
    print(f"       mapping_id={mapping_id}")

    # --- Step 3: calculation ---
    print("\n[3] Run calculation (factor version 2023)")
    r = client.post(
        "/api/v1/calculations",
        json={"upload_id": upload_id, "emission_factor_version": "2023"},
    )
    check(r.status_code == 202, f"POST /calculations → 202 (got {r.status_code})")
    job = r.json()
    job_id = job["job_id"]
    check(job["status"] == "completed", f"job.status == completed (got {job['status']})")
    print(f"       job_id={job_id}")

    # --- Step 4: results ---
    print("\n[4] Fetch results")
    r = client.get(f"/api/v1/calculations/{job_id}/results")
    check(r.status_code == 200, f"GET /results → 200 (got {r.status_code})")
    result = r.json()
    rows = result["rows"]
    summary = result["summary"]

    check(len(rows) == 5, f"5 result rows (got {len(rows)})")
    check(summary["grand_total"] > 0, f"grand_total > 0 (got {summary['grand_total']})")
    check(
        abs(summary["scope2_total"] - 453.0) < 0.1,
        f"scope2 == 453.0 kg-CO2e (electricity 1000kWh × 0.453) got {summary['scope2_total']}",
    )
    check(
        abs(summary["scope1_total"] - 563.5) < 0.1,
        f"scope1 == 563.5 kg-CO2e (gas 150m³ + gasoline 100L) got {summary['scope1_total']}",
    )

    print("\n  Scope summary:")
    print(f"    Scope 1: {summary['scope1_total']:>8.2f} kg-CO2e")
    print(f"    Scope 2: {summary['scope2_total']:>8.2f} kg-CO2e")
    print(f"    Scope 3: {summary['scope3_total']:>8.2f} kg-CO2e")
    print(f"    TOTAL  : {summary['grand_total']:>8.2f} kg-CO2e")
    print(f"    Rows   : {summary['calculated_row_count']} calculated, {summary['unclassified_count']} unclassified")

    # --- Step 5: recalculation ---
    print("\n[5] Recalculate with factor version 2021")
    r = client.post(
        f"/api/v1/calculations/{job_id}/recalculate",
        json={"emission_factor_version": "2021"},
    )
    check(r.status_code == 202, f"POST /recalculate → 202 (got {r.status_code})")
    job2_id = r.json()["job_id"]
    r2 = client.get(f"/api/v1/calculations/{job2_id}/results")
    total2 = r2.json()["summary"]["grand_total"]
    check(total2 != summary["grand_total"], f"recalc total differs (2023={summary['grand_total']}, 2021={total2})")
    print(f"       2021 grand_total={total2:.2f} kg-CO2e (vs 2023: {summary['grand_total']:.2f})")

    # --- Step 5b: comparison / delta ---
    print("\n[5b] Compare 2023 vs 2021 (Delta)")
    r = client.get(f"/api/v1/comparisons?job_ids={job_id},{job2_id}")
    check(r.status_code == 200, f"GET /comparisons → 200 (got {r.status_code})")
    cmp = r.json()
    check("comparisons" in cmp, "response has 'comparisons'")
    check(len(cmp["comparisons"]) == 2, f"2 entries (got {len(cmp['comparisons'])})")
    check("delta" in cmp, "response has 'delta'")
    delta = cmp["delta"]
    print(f"       Delta  scope1={delta['scope1']:+.2f}  scope2={delta['scope2']:+.2f}  scope3={delta['scope3']:+.2f}  total={delta['grand_total']:+.2f}")

    # --- Step 6: CSV export ---
    print("\n[6] CSV export")
    r = client.get(f"/api/v1/reports/{job_id}/csv")
    check(r.status_code == 200, f"GET /reports/csv → 200 (got {r.status_code})")
    check("排出量(kg-CO2e)" in r.text, "CSV contains header '排出量(kg-CO2e)'")
    check("Scope2合計" in r.text, "CSV contains '集計' section")
    lines = [l for l in r.text.splitlines() if l.strip()]
    print(f"       {len(lines)} lines in CSV")

    # --- Step 7: write CSV artifact ---
    if csv_out:
        print(f"\n[7] Writing CSV report to {csv_out}")
        r = client.get(f"/api/v1/reports/{job_id}/csv")
        check(r.status_code == 200, f"GET /reports/csv for file export → 200 (got {r.status_code})")
        with open(csv_out, "w", encoding="utf-8") as fh:
            fh.write(r.text)
        check(os.path.getsize(csv_out) > 0, f"{csv_out} written with content")
        print(f"       Wrote {os.path.getsize(csv_out)} bytes")

    # --- Step 8: write HTML report ---
    if html_out:
        print(f"\n[8] Writing HTML report to {html_out}")
        generate_html_report(summary, html_out)
        check(os.path.getsize(html_out) > 0, f"{html_out} written with content")
        print(f"       Wrote {os.path.getsize(html_out)} bytes")

    print("\n=== ALL CHECKS PASSED ===")
    print(f"Grand total: {summary['grand_total']:.2f} kg-CO2e from accounting_sample.csv")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv-out", metavar="PATH", help="Write CSV report to this path")
    parser.add_argument("--html-out", metavar="PATH", help="Write HTML report to this path")
    args = parser.parse_args()
    main(csv_out=args.csv_out, html_out=args.html_out)
